### ISSUE TITLE
Add simple CLI API

### ISSUE THREAD

**Issue by matthewfeickert** [zbilodea/odapt#29]
:wave: This is great to see! What would be nice is if there was also a simple CLI API (using `Click` or something similar) for `hadd` that would take the form of something like

```
odapt hadd [OUTPUT_FILE] [INPUT_FILES]
```

**Comment by zbilodea** [comment]
I'm on it! Thanks for the feedback!

**Comment by alexander-held** [comment]
One extra benefit from a command line interface would be that we could use [pipx](https://github.com/pypa/pipx) to run the `hadd` command in an isolated environment. That's very convenient for people who still regularly work in Python environments with older awkward versions<2 (including me).
